/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalentosRouteImport } from './routes/talentos'
import { Route as OperacaoRouteImport } from './routes/operacao'
import { Route as EstrategiaRouteImport } from './routes/estrategia'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesCicloCycleIdRouteImport } from './routes/configuracoes.ciclo.$cycleId'

const TalentosRoute = TalentosRouteImport.update({
  id: '/talentos',
  path: '/talentos',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacaoRoute = OperacaoRouteImport.update({
  id: '/operacao',
  path: '/operacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EstrategiaRoute = EstrategiaRouteImport.update({
  id: '/estrategia',
  path: '/estrategia',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesCicloCycleIdRoute =
  ConfiguracoesCicloCycleIdRouteImport.update({
    id: '/ciclo/$cycleId',
    path: '/ciclo/$cycleId',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/estrategia': typeof EstrategiaRoute
  '/operacao': typeof OperacaoRoute
  '/talentos': typeof TalentosRoute
  '/configuracoes/ciclo/$cycleId': typeof ConfiguracoesCicloCycleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/estrategia': typeof EstrategiaRoute
  '/operacao': typeof OperacaoRoute
  '/talentos': typeof TalentosRoute
  '/configuracoes/ciclo/$cycleId': typeof ConfiguracoesCicloCycleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/estrategia': typeof EstrategiaRoute
  '/operacao': typeof OperacaoRoute
  '/talentos': typeof TalentosRoute
  '/configuracoes/ciclo/$cycleId': typeof ConfiguracoesCicloCycleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/estrategia'
    | '/operacao'
    | '/talentos'
    | '/configuracoes/ciclo/$cycleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/estrategia'
    | '/operacao'
    | '/talentos'
    | '/configuracoes/ciclo/$cycleId'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/estrategia'
    | '/operacao'
    | '/talentos'
    | '/configuracoes/ciclo/$cycleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  EstrategiaRoute: typeof EstrategiaRoute
  OperacaoRoute: typeof OperacaoRoute
  TalentosRoute: typeof TalentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talentos': {
      id: '/talentos'
      path: '/talentos'
      fullPath: '/talentos'
      preLoaderRoute: typeof TalentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacao': {
      id: '/operacao'
      path: '/operacao'
      fullPath: '/operacao'
      preLoaderRoute: typeof OperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrategia': {
      id: '/estrategia'
      path: '/estrategia'
      fullPath: '/estrategia'
      preLoaderRoute: typeof EstrategiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/ciclo/$cycleId': {
      id: '/configuracoes/ciclo/$cycleId'
      path: '/ciclo/$cycleId'
      fullPath: '/configuracoes/ciclo/$cycleId'
      preLoaderRoute: typeof ConfiguracoesCicloCycleIdRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
  }
}

interface ConfiguracoesRouteChildren {
  ConfiguracoesCicloCycleIdRoute: typeof ConfiguracoesCicloCycleIdRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesCicloCycleIdRoute: ConfiguracoesCicloCycleIdRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  EstrategiaRoute: EstrategiaRoute,
  OperacaoRoute: OperacaoRoute,
  TalentosRoute: TalentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
