/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreinamentosRouteImport } from './routes/treinamentos'
import { Route as TalentosRouteImport } from './routes/talentos'
import { Route as RecompensaReconhecimentoRouteImport } from './routes/recompensa-reconhecimento'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OrganogramaRouteImport } from './routes/organograma'
import { Route as OperacaoRouteImport } from './routes/operacao'
import { Route as EstrategiaRouteImport } from './routes/estrategia'
import { Route as EngajamentoCulturaRouteImport } from './routes/engajamento-cultura'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesCicloCycleIdRouteImport } from './routes/configuracoes.ciclo.$cycleId'

const TreinamentosRoute = TreinamentosRouteImport.update({
  id: '/treinamentos',
  path: '/treinamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentosRoute = TalentosRouteImport.update({
  id: '/talentos',
  path: '/talentos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecompensaReconhecimentoRoute =
  RecompensaReconhecimentoRouteImport.update({
    id: '/recompensa-reconhecimento',
    path: '/recompensa-reconhecimento',
    getParentRoute: () => rootRouteImport,
  } as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganogramaRoute = OrganogramaRouteImport.update({
  id: '/organograma',
  path: '/organograma',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacaoRoute = OperacaoRouteImport.update({
  id: '/operacao',
  path: '/operacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EstrategiaRoute = EstrategiaRouteImport.update({
  id: '/estrategia',
  path: '/estrategia',
  getParentRoute: () => rootRouteImport,
} as any)
const EngajamentoCulturaRoute = EngajamentoCulturaRouteImport.update({
  id: '/engajamento-cultura',
  path: '/engajamento-cultura',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesCicloCycleIdRoute =
  ConfiguracoesCicloCycleIdRouteImport.update({
    id: '/ciclo/$cycleId',
    path: '/ciclo/$cycleId',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/engajamento-cultura': typeof EngajamentoCulturaRoute
  '/estrategia': typeof EstrategiaRoute
  '/operacao': typeof OperacaoRoute
  '/organograma': typeof OrganogramaRoute
  '/perfil': typeof PerfilRoute
  '/recompensa-reconhecimento': typeof RecompensaReconhecimentoRoute
  '/talentos': typeof TalentosRoute
  '/treinamentos': typeof TreinamentosRoute
  '/configuracoes/ciclo/$cycleId': typeof ConfiguracoesCicloCycleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/engajamento-cultura': typeof EngajamentoCulturaRoute
  '/estrategia': typeof EstrategiaRoute
  '/operacao': typeof OperacaoRoute
  '/organograma': typeof OrganogramaRoute
  '/perfil': typeof PerfilRoute
  '/recompensa-reconhecimento': typeof RecompensaReconhecimentoRoute
  '/talentos': typeof TalentosRoute
  '/treinamentos': typeof TreinamentosRoute
  '/configuracoes/ciclo/$cycleId': typeof ConfiguracoesCicloCycleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/engajamento-cultura': typeof EngajamentoCulturaRoute
  '/estrategia': typeof EstrategiaRoute
  '/operacao': typeof OperacaoRoute
  '/organograma': typeof OrganogramaRoute
  '/perfil': typeof PerfilRoute
  '/recompensa-reconhecimento': typeof RecompensaReconhecimentoRoute
  '/talentos': typeof TalentosRoute
  '/treinamentos': typeof TreinamentosRoute
  '/configuracoes/ciclo/$cycleId': typeof ConfiguracoesCicloCycleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/engajamento-cultura'
    | '/estrategia'
    | '/operacao'
    | '/organograma'
    | '/perfil'
    | '/recompensa-reconhecimento'
    | '/talentos'
    | '/treinamentos'
    | '/configuracoes/ciclo/$cycleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/engajamento-cultura'
    | '/estrategia'
    | '/operacao'
    | '/organograma'
    | '/perfil'
    | '/recompensa-reconhecimento'
    | '/talentos'
    | '/treinamentos'
    | '/configuracoes/ciclo/$cycleId'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/engajamento-cultura'
    | '/estrategia'
    | '/operacao'
    | '/organograma'
    | '/perfil'
    | '/recompensa-reconhecimento'
    | '/talentos'
    | '/treinamentos'
    | '/configuracoes/ciclo/$cycleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  EngajamentoCulturaRoute: typeof EngajamentoCulturaRoute
  EstrategiaRoute: typeof EstrategiaRoute
  OperacaoRoute: typeof OperacaoRoute
  OrganogramaRoute: typeof OrganogramaRoute
  PerfilRoute: typeof PerfilRoute
  RecompensaReconhecimentoRoute: typeof RecompensaReconhecimentoRoute
  TalentosRoute: typeof TalentosRoute
  TreinamentosRoute: typeof TreinamentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treinamentos': {
      id: '/treinamentos'
      path: '/treinamentos'
      fullPath: '/treinamentos'
      preLoaderRoute: typeof TreinamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talentos': {
      id: '/talentos'
      path: '/talentos'
      fullPath: '/talentos'
      preLoaderRoute: typeof TalentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recompensa-reconhecimento': {
      id: '/recompensa-reconhecimento'
      path: '/recompensa-reconhecimento'
      fullPath: '/recompensa-reconhecimento'
      preLoaderRoute: typeof RecompensaReconhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organograma': {
      id: '/organograma'
      path: '/organograma'
      fullPath: '/organograma'
      preLoaderRoute: typeof OrganogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacao': {
      id: '/operacao'
      path: '/operacao'
      fullPath: '/operacao'
      preLoaderRoute: typeof OperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrategia': {
      id: '/estrategia'
      path: '/estrategia'
      fullPath: '/estrategia'
      preLoaderRoute: typeof EstrategiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engajamento-cultura': {
      id: '/engajamento-cultura'
      path: '/engajamento-cultura'
      fullPath: '/engajamento-cultura'
      preLoaderRoute: typeof EngajamentoCulturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/ciclo/$cycleId': {
      id: '/configuracoes/ciclo/$cycleId'
      path: '/ciclo/$cycleId'
      fullPath: '/configuracoes/ciclo/$cycleId'
      preLoaderRoute: typeof ConfiguracoesCicloCycleIdRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
  }
}

interface ConfiguracoesRouteChildren {
  ConfiguracoesCicloCycleIdRoute: typeof ConfiguracoesCicloCycleIdRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesCicloCycleIdRoute: ConfiguracoesCicloCycleIdRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  EngajamentoCulturaRoute: EngajamentoCulturaRoute,
  EstrategiaRoute: EstrategiaRoute,
  OperacaoRoute: OperacaoRoute,
  OrganogramaRoute: OrganogramaRoute,
  PerfilRoute: PerfilRoute,
  RecompensaReconhecimentoRoute: RecompensaReconhecimentoRoute,
  TalentosRoute: TalentosRoute,
  TreinamentosRoute: TreinamentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
